# Generated by Django 4.1.5 on 2023-01-30 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_LMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworks',
            name='solution_file',
            field=models.FileField(blank=True, null=True, upload_to='upload/solutions'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solutions',
            name='file',
            field=models.FileField(upload_to='', verbose_name='uploads/studentsolutions'),
        ),
    ]
