# Generated by Django 4.1.5 on 2023-01-30 20:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Simple_LMS', '0002_homeworks_solution_file_notifications_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homeworks',
            new_name='Homework',
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameModel(
            old_name='Solutions',
            new_name='Solution',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
