# Generated by Django 4.1.5 on 2023-01-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_LMS', '0005_alter_notification_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
