# Generated by Django 4.1.5 on 2023-01-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_LMS', '0008_homework_deadline_homework_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='solution_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/solutions'),
        ),
    ]
