# Generated by Django 4.1.5 on 2023-02-03 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_LMS', '0014_note_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='number',
        ),
        migrations.RemoveField(
            model_name='note',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='course',
        ),
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(default='Course', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='file',
            field=models.FileField(upload_to='uploads/homeworks'),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to='uploads/notes'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='file',
            field=models.FileField(upload_to='uploads/student_solutions'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='uploads/videos'),
        ),
    ]
