# Generated by Django 4.1.5 on 2023-02-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_LMS', '0015_remove_note_number_remove_note_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='max_score',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
