# Generated by Django 4.1.5 on 2023-02-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_LMS', '0017_alter_course_is_active_alter_note_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_final',
            field=models.BooleanField(default=True),
        ),
    ]
