# Generated by Django 4.1.7 on 2023-05-18 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_LMS', '0021_remove_course_students_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Simple_LMS.course'),
            preserve_default=False,
        ),
    ]
