# Generated by Django 4.1.7 on 2023-05-18 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_LMS', '0022_solution_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Simple_LMS.course'),
            preserve_default=False,
        ),
    ]
