# Generated by Django 4.1.7 on 2023-05-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_LMS', '0023_notification_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='score',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=4),
            preserve_default=False,
        ),
    ]
