# Generated by Django 4.1.7 on 2023-05-19 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Simple_LMS', '0024_enrollment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
